// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: pipeline.proto

package pipelinepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetUploadCompleted struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	AssetId                    string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrgId                      string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	SourceUri                  string                 `protobuf:"bytes,3,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	RequestedSubtitleLanguages []string               `protobuf:"bytes,4,rep,name=requested_subtitle_languages,json=requestedSubtitleLanguages,proto3" json:"requested_subtitle_languages,omitempty"`
	IdempotencyKey             string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	TimestampUnix              int64                  `protobuf:"varint,6,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *AssetUploadCompleted) Reset() {
	*x = AssetUploadCompleted{}
	mi := &file_pipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetUploadCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetUploadCompleted) ProtoMessage() {}

func (x *AssetUploadCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetUploadCompleted.ProtoReflect.Descriptor instead.
func (*AssetUploadCompleted) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{0}
}

func (x *AssetUploadCompleted) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetUploadCompleted) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *AssetUploadCompleted) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *AssetUploadCompleted) GetRequestedSubtitleLanguages() []string {
	if x != nil {
		return x.RequestedSubtitleLanguages
	}
	return nil
}

func (x *AssetUploadCompleted) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *AssetUploadCompleted) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type ProbeRequested struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId        string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	SourceUri      string                 `protobuf:"bytes,3,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	OrgId          string                 `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Attempt        int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProbeRequested) Reset() {
	*x = ProbeRequested{}
	mi := &file_pipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequested) ProtoMessage() {}

func (x *ProbeRequested) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequested.ProtoReflect.Descriptor instead.
func (*ProbeRequested) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{1}
}

func (x *ProbeRequested) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ProbeRequested) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ProbeRequested) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *ProbeRequested) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ProbeRequested) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ProbeRequested) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ProbeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      float64                `protobuf:"fixed64,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	VideoCodec    string                 `protobuf:"bytes,4,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"`
	AudioCodec    string                 `protobuf:"bytes,5,opt,name=audio_codec,json=audioCodec,proto3" json:"audio_codec,omitempty"`
	BitRate       int64                  `protobuf:"varint,6,opt,name=bit_rate,json=bitRate,proto3" json:"bit_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResult) Reset() {
	*x = ProbeResult{}
	mi := &file_pipeline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult) ProtoMessage() {}

func (x *ProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult.ProtoReflect.Descriptor instead.
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{2}
}

func (x *ProbeResult) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ProbeResult) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ProbeResult) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ProbeResult) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

func (x *ProbeResult) GetAudioCodec() string {
	if x != nil {
		return x.AudioCodec
	}
	return ""
}

func (x *ProbeResult) GetBitRate() int64 {
	if x != nil {
		return x.BitRate
	}
	return 0
}

type ProbeCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	SourceUri     string                 `protobuf:"bytes,4,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	Result        *ProbeResult           `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	Attempt       int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,7,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeCompleted) Reset() {
	*x = ProbeCompleted{}
	mi := &file_pipeline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeCompleted) ProtoMessage() {}

func (x *ProbeCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeCompleted.ProtoReflect.Descriptor instead.
func (*ProbeCompleted) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{3}
}

func (x *ProbeCompleted) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ProbeCompleted) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ProbeCompleted) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ProbeCompleted) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *ProbeCompleted) GetResult() *ProbeResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ProbeCompleted) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ProbeCompleted) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type ProbeFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Attempt       int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,7,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeFailed) Reset() {
	*x = ProbeFailed{}
	mi := &file_pipeline_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeFailed) ProtoMessage() {}

func (x *ProbeFailed) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeFailed.ProtoReflect.Descriptor instead.
func (*ProbeFailed) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{4}
}

func (x *ProbeFailed) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ProbeFailed) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ProbeFailed) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ProbeFailed) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ProbeFailed) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ProbeFailed) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ProbeFailed) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type TranscodeRequested struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId        string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	SourceUri      string                 `protobuf:"bytes,3,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	OutputPrefix   string                 `protobuf:"bytes,4,opt,name=output_prefix,json=outputPrefix,proto3" json:"output_prefix,omitempty"`
	OrgId          string                 `protobuf:"bytes,5,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Attempt        int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TranscodeRequested) Reset() {
	*x = TranscodeRequested{}
	mi := &file_pipeline_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeRequested) ProtoMessage() {}

func (x *TranscodeRequested) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeRequested.ProtoReflect.Descriptor instead.
func (*TranscodeRequested) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{5}
}

func (x *TranscodeRequested) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TranscodeRequested) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *TranscodeRequested) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *TranscodeRequested) GetOutputPrefix() string {
	if x != nil {
		return x.OutputPrefix
	}
	return ""
}

func (x *TranscodeRequested) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *TranscodeRequested) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *TranscodeRequested) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type TranscodeCompleted struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	RunId                  string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId                string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrgId                  string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	OutputPrefix           string                 `protobuf:"bytes,4,opt,name=output_prefix,json=outputPrefix,proto3" json:"output_prefix,omitempty"`
	MasterPlaylistLocation string                 `protobuf:"bytes,5,opt,name=master_playlist_location,json=masterPlaylistLocation,proto3" json:"master_playlist_location,omitempty"`
	RenditionCount         int32                  `protobuf:"varint,6,opt,name=rendition_count,json=renditionCount,proto3" json:"rendition_count,omitempty"`
	Attempt                int32                  `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	TimestampUnix          int64                  `protobuf:"varint,8,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TranscodeCompleted) Reset() {
	*x = TranscodeCompleted{}
	mi := &file_pipeline_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeCompleted) ProtoMessage() {}

func (x *TranscodeCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeCompleted.ProtoReflect.Descriptor instead.
func (*TranscodeCompleted) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{6}
}

func (x *TranscodeCompleted) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TranscodeCompleted) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *TranscodeCompleted) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *TranscodeCompleted) GetOutputPrefix() string {
	if x != nil {
		return x.OutputPrefix
	}
	return ""
}

func (x *TranscodeCompleted) GetMasterPlaylistLocation() string {
	if x != nil {
		return x.MasterPlaylistLocation
	}
	return ""
}

func (x *TranscodeCompleted) GetRenditionCount() int32 {
	if x != nil {
		return x.RenditionCount
	}
	return 0
}

func (x *TranscodeCompleted) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *TranscodeCompleted) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type TranscodeFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Attempt       int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,7,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeFailed) Reset() {
	*x = TranscodeFailed{}
	mi := &file_pipeline_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeFailed) ProtoMessage() {}

func (x *TranscodeFailed) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeFailed.ProtoReflect.Descriptor instead.
func (*TranscodeFailed) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{7}
}

func (x *TranscodeFailed) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TranscodeFailed) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *TranscodeFailed) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *TranscodeFailed) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TranscodeFailed) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TranscodeFailed) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *TranscodeFailed) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type ThumbnailRequested struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId        string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	SourceUri      string                 `protobuf:"bytes,3,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	OutputPrefix   string                 `protobuf:"bytes,4,opt,name=output_prefix,json=outputPrefix,proto3" json:"output_prefix,omitempty"`
	OrgId          string                 `protobuf:"bytes,5,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Attempt        int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ThumbnailRequested) Reset() {
	*x = ThumbnailRequested{}
	mi := &file_pipeline_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailRequested) ProtoMessage() {}

func (x *ThumbnailRequested) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailRequested.ProtoReflect.Descriptor instead.
func (*ThumbnailRequested) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{8}
}

func (x *ThumbnailRequested) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ThumbnailRequested) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ThumbnailRequested) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *ThumbnailRequested) GetOutputPrefix() string {
	if x != nil {
		return x.OutputPrefix
	}
	return ""
}

func (x *ThumbnailRequested) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ThumbnailRequested) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ThumbnailRequested) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ThumbnailCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Attempt       int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,6,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailCompleted) Reset() {
	*x = ThumbnailCompleted{}
	mi := &file_pipeline_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailCompleted) ProtoMessage() {}

func (x *ThumbnailCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailCompleted.ProtoReflect.Descriptor instead.
func (*ThumbnailCompleted) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{9}
}

func (x *ThumbnailCompleted) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ThumbnailCompleted) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ThumbnailCompleted) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ThumbnailCompleted) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ThumbnailCompleted) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ThumbnailCompleted) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type ThumbnailFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Attempt       int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,7,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailFailed) Reset() {
	*x = ThumbnailFailed{}
	mi := &file_pipeline_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailFailed) ProtoMessage() {}

func (x *ThumbnailFailed) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailFailed.ProtoReflect.Descriptor instead.
func (*ThumbnailFailed) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{10}
}

func (x *ThumbnailFailed) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ThumbnailFailed) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ThumbnailFailed) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ThumbnailFailed) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ThumbnailFailed) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ThumbnailFailed) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ThumbnailFailed) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type StoryboardRequested struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId        string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	SourceUri      string                 `protobuf:"bytes,3,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	OutputPrefix   string                 `protobuf:"bytes,4,opt,name=output_prefix,json=outputPrefix,proto3" json:"output_prefix,omitempty"`
	OrgId          string                 `protobuf:"bytes,5,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Attempt        int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoryboardRequested) Reset() {
	*x = StoryboardRequested{}
	mi := &file_pipeline_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryboardRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryboardRequested) ProtoMessage() {}

func (x *StoryboardRequested) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryboardRequested.ProtoReflect.Descriptor instead.
func (*StoryboardRequested) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{11}
}

func (x *StoryboardRequested) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StoryboardRequested) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *StoryboardRequested) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *StoryboardRequested) GetOutputPrefix() string {
	if x != nil {
		return x.OutputPrefix
	}
	return ""
}

func (x *StoryboardRequested) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *StoryboardRequested) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *StoryboardRequested) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type StoryboardCompleted struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId        string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrgId          string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	SpriteLocation string                 `protobuf:"bytes,4,opt,name=sprite_location,json=spriteLocation,proto3" json:"sprite_location,omitempty"`
	VttLocation    string                 `protobuf:"bytes,5,opt,name=vtt_location,json=vttLocation,proto3" json:"vtt_location,omitempty"`
	Attempt        int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	TimestampUnix  int64                  `protobuf:"varint,7,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoryboardCompleted) Reset() {
	*x = StoryboardCompleted{}
	mi := &file_pipeline_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryboardCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryboardCompleted) ProtoMessage() {}

func (x *StoryboardCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryboardCompleted.ProtoReflect.Descriptor instead.
func (*StoryboardCompleted) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{12}
}

func (x *StoryboardCompleted) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StoryboardCompleted) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *StoryboardCompleted) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *StoryboardCompleted) GetSpriteLocation() string {
	if x != nil {
		return x.SpriteLocation
	}
	return ""
}

func (x *StoryboardCompleted) GetVttLocation() string {
	if x != nil {
		return x.VttLocation
	}
	return ""
}

func (x *StoryboardCompleted) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *StoryboardCompleted) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type StoryboardFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Attempt       int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,7,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryboardFailed) Reset() {
	*x = StoryboardFailed{}
	mi := &file_pipeline_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryboardFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryboardFailed) ProtoMessage() {}

func (x *StoryboardFailed) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryboardFailed.ProtoReflect.Descriptor instead.
func (*StoryboardFailed) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{13}
}

func (x *StoryboardFailed) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StoryboardFailed) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *StoryboardFailed) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *StoryboardFailed) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *StoryboardFailed) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *StoryboardFailed) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *StoryboardFailed) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type SubtitleRequested struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId        string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	SourceUri      string                 `protobuf:"bytes,3,opt,name=source_uri,json=sourceUri,proto3" json:"source_uri,omitempty"`
	Language       string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	OutputPrefix   string                 `protobuf:"bytes,5,opt,name=output_prefix,json=outputPrefix,proto3" json:"output_prefix,omitempty"`
	OrgId          string                 `protobuf:"bytes,6,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Attempt        int32                  `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubtitleRequested) Reset() {
	*x = SubtitleRequested{}
	mi := &file_pipeline_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtitleRequested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtitleRequested) ProtoMessage() {}

func (x *SubtitleRequested) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtitleRequested.ProtoReflect.Descriptor instead.
func (*SubtitleRequested) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{14}
}

func (x *SubtitleRequested) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SubtitleRequested) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *SubtitleRequested) GetSourceUri() string {
	if x != nil {
		return x.SourceUri
	}
	return ""
}

func (x *SubtitleRequested) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SubtitleRequested) GetOutputPrefix() string {
	if x != nil {
		return x.OutputPrefix
	}
	return ""
}

func (x *SubtitleRequested) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SubtitleRequested) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *SubtitleRequested) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type SubtitleCompleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	VttLocation   string                 `protobuf:"bytes,5,opt,name=vtt_location,json=vttLocation,proto3" json:"vtt_location,omitempty"`
	Attempt       int32                  `protobuf:"varint,6,opt,name=attempt,proto3" json:"attempt,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,7,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtitleCompleted) Reset() {
	*x = SubtitleCompleted{}
	mi := &file_pipeline_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtitleCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtitleCompleted) ProtoMessage() {}

func (x *SubtitleCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtitleCompleted.ProtoReflect.Descriptor instead.
func (*SubtitleCompleted) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{15}
}

func (x *SubtitleCompleted) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SubtitleCompleted) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *SubtitleCompleted) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SubtitleCompleted) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SubtitleCompleted) GetVttLocation() string {
	if x != nil {
		return x.VttLocation
	}
	return ""
}

func (x *SubtitleCompleted) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *SubtitleCompleted) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type SubtitleFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Attempt       int32                  `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,8,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubtitleFailed) Reset() {
	*x = SubtitleFailed{}
	mi := &file_pipeline_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubtitleFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubtitleFailed) ProtoMessage() {}

func (x *SubtitleFailed) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubtitleFailed.ProtoReflect.Descriptor instead.
func (*SubtitleFailed) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{16}
}

func (x *SubtitleFailed) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SubtitleFailed) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *SubtitleFailed) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SubtitleFailed) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SubtitleFailed) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SubtitleFailed) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SubtitleFailed) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *SubtitleFailed) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type PipelineRunCompleted struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RunId             string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId           string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrgId             string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	PlaybackId        string                 `protobuf:"bytes,4,opt,name=playback_id,json=playbackId,proto3" json:"playback_id,omitempty"`
	ArtifactLocations map[string]string      `protobuf:"bytes,5,rep,name=artifact_locations,json=artifactLocations,proto3" json:"artifact_locations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimestampUnix     int64                  `protobuf:"varint,6,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PipelineRunCompleted) Reset() {
	*x = PipelineRunCompleted{}
	mi := &file_pipeline_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineRunCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineRunCompleted) ProtoMessage() {}

func (x *PipelineRunCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineRunCompleted.ProtoReflect.Descriptor instead.
func (*PipelineRunCompleted) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{17}
}

func (x *PipelineRunCompleted) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *PipelineRunCompleted) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *PipelineRunCompleted) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *PipelineRunCompleted) GetPlaybackId() string {
	if x != nil {
		return x.PlaybackId
	}
	return ""
}

func (x *PipelineRunCompleted) GetArtifactLocations() map[string]string {
	if x != nil {
		return x.ArtifactLocations
	}
	return nil
}

func (x *PipelineRunCompleted) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

type PipelineRunFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,6,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineRunFailed) Reset() {
	*x = PipelineRunFailed{}
	mi := &file_pipeline_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineRunFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineRunFailed) ProtoMessage() {}

func (x *PipelineRunFailed) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineRunFailed.ProtoReflect.Descriptor instead.
func (*PipelineRunFailed) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{18}
}

func (x *PipelineRunFailed) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *PipelineRunFailed) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *PipelineRunFailed) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *PipelineRunFailed) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *PipelineRunFailed) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PipelineRunFailed) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

var File_pipeline_proto protoreflect.FileDescriptor

const file_pipeline_proto_rawDesc = "" +
	"\n" +
	"\x0epipeline.proto\x12\bpipeline\"\xf9\x01\n" +
	"\x14AssetUploadCompleted\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x03 \x01(\tR\tsourceUri\x12@\n" +
	"\x1crequested_subtitle_languages\x18\x04 \x03(\tR\x1arequestedSubtitleLanguages\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0etimestamp_unix\x18\x06 \x01(\x03R\rtimestampUnix\"\xbb\x01\n" +
	"\x0eProbeRequested\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x03 \x01(\tR\tsourceUri\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\"\xb4\x01\n" +
	"\vProbeResult\x12\x1a\n" +
	"\bduration\x18\x01 \x01(\x01R\bduration\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1f\n" +
	"\vvideo_codec\x18\x04 \x01(\tR\n" +
	"videoCodec\x12\x1f\n" +
	"\vaudio_codec\x18\x05 \x01(\tR\n" +
	"audioCodec\x12\x19\n" +
	"\bbit_rate\x18\x06 \x01(\x03R\abitRate\"\xe8\x01\n" +
	"\x0eProbeCompleted\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x04 \x01(\tR\tsourceUri\x12-\n" +
	"\x06result\x18\x05 \x01(\v2\x15.pipeline.ProbeResultR\x06result\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12%\n" +
	"\x0etimestamp_unix\x18\a \x01(\x03R\rtimestampUnix\"\xdb\x01\n" +
	"\vProbeFailed\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12%\n" +
	"\x0etimestamp_unix\x18\a \x01(\x03R\rtimestampUnix\"\xe4\x01\n" +
	"\x12TranscodeRequested\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x03 \x01(\tR\tsourceUri\x12#\n" +
	"\routput_prefix\x18\x04 \x01(\tR\foutputPrefix\x12\x15\n" +
	"\x06org_id\x18\x05 \x01(\tR\x05orgId\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\"\xa6\x02\n" +
	"\x12TranscodeCompleted\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12#\n" +
	"\routput_prefix\x18\x04 \x01(\tR\foutputPrefix\x128\n" +
	"\x18master_playlist_location\x18\x05 \x01(\tR\x16masterPlaylistLocation\x12'\n" +
	"\x0frendition_count\x18\x06 \x01(\x05R\x0erenditionCount\x12\x18\n" +
	"\aattempt\x18\a \x01(\x05R\aattempt\x12%\n" +
	"\x0etimestamp_unix\x18\b \x01(\x03R\rtimestampUnix\"\xdf\x01\n" +
	"\x0fTranscodeFailed\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12%\n" +
	"\x0etimestamp_unix\x18\a \x01(\x03R\rtimestampUnix\"\xe4\x01\n" +
	"\x12ThumbnailRequested\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x03 \x01(\tR\tsourceUri\x12#\n" +
	"\routput_prefix\x18\x04 \x01(\tR\foutputPrefix\x12\x15\n" +
	"\x06org_id\x18\x05 \x01(\tR\x05orgId\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\"\xba\x01\n" +
	"\x12ThumbnailCompleted\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\x12%\n" +
	"\x0etimestamp_unix\x18\x06 \x01(\x03R\rtimestampUnix\"\xdf\x01\n" +
	"\x0fThumbnailFailed\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12%\n" +
	"\x0etimestamp_unix\x18\a \x01(\x03R\rtimestampUnix\"\xe5\x01\n" +
	"\x13StoryboardRequested\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x03 \x01(\tR\tsourceUri\x12#\n" +
	"\routput_prefix\x18\x04 \x01(\tR\foutputPrefix\x12\x15\n" +
	"\x06org_id\x18\x05 \x01(\tR\x05orgId\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\"\xeb\x01\n" +
	"\x13StoryboardCompleted\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12'\n" +
	"\x0fsprite_location\x18\x04 \x01(\tR\x0espriteLocation\x12!\n" +
	"\fvtt_location\x18\x05 \x01(\tR\vvttLocation\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12%\n" +
	"\x0etimestamp_unix\x18\a \x01(\x03R\rtimestampUnix\"\xe0\x01\n" +
	"\x10StoryboardFailed\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12%\n" +
	"\x0etimestamp_unix\x18\a \x01(\x03R\rtimestampUnix\"\xff\x01\n" +
	"\x11SubtitleRequested\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x1d\n" +
	"\n" +
	"source_uri\x18\x03 \x01(\tR\tsourceUri\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12#\n" +
	"\routput_prefix\x18\x05 \x01(\tR\foutputPrefix\x12\x15\n" +
	"\x06org_id\x18\x06 \x01(\tR\x05orgId\x12\x18\n" +
	"\aattempt\x18\a \x01(\x05R\aattempt\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\"\xdc\x01\n" +
	"\x11SubtitleCompleted\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12!\n" +
	"\fvtt_location\x18\x05 \x01(\tR\vvttLocation\x12\x18\n" +
	"\aattempt\x18\x06 \x01(\x05R\aattempt\x12%\n" +
	"\x0etimestamp_unix\x18\a \x01(\x03R\rtimestampUnix\"\xfa\x01\n" +
	"\x0eSubtitleFailed\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12\x18\n" +
	"\aattempt\x18\a \x01(\x05R\aattempt\x12%\n" +
	"\x0etimestamp_unix\x18\b \x01(\x03R\rtimestampUnix\"\xd3\x02\n" +
	"\x14PipelineRunCompleted\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x1f\n" +
	"\vplayback_id\x18\x04 \x01(\tR\n" +
	"playbackId\x12d\n" +
	"\x12artifact_locations\x18\x05 \x03(\v25.pipeline.PipelineRunCompleted.ArtifactLocationsEntryR\x11artifactLocations\x12%\n" +
	"\x0etimestamp_unix\x18\x06 \x01(\x03R\rtimestampUnix\x1aD\n" +
	"\x16ArtifactLocationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x01\n" +
	"\x11PipelineRunFailed\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0etimestamp_unix\x18\x06 \x01(\x03R\rtimestampUnixB:Z8github.com/Ajay01103/go-notion/pkg/pipelinepb;pipelinepbb\x06proto3"

var (
	file_pipeline_proto_rawDescOnce sync.Once
	file_pipeline_proto_rawDescData []byte
)

func file_pipeline_proto_rawDescGZIP() []byte {
	file_pipeline_proto_rawDescOnce.Do(func() {
		file_pipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pipeline_proto_rawDesc), len(file_pipeline_proto_rawDesc)))
	})
	return file_pipeline_proto_rawDescData
}

var file_pipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pipeline_proto_goTypes = []any{
	(*AssetUploadCompleted)(nil), // 0: pipeline.AssetUploadCompleted
	(*ProbeRequested)(nil),       // 1: pipeline.ProbeRequested
	(*ProbeResult)(nil),          // 2: pipeline.ProbeResult
	(*ProbeCompleted)(nil),       // 3: pipeline.ProbeCompleted
	(*ProbeFailed)(nil),          // 4: pipeline.ProbeFailed
	(*TranscodeRequested)(nil),   // 5: pipeline.TranscodeRequested
	(*TranscodeCompleted)(nil),   // 6: pipeline.TranscodeCompleted
	(*TranscodeFailed)(nil),      // 7: pipeline.TranscodeFailed
	(*ThumbnailRequested)(nil),   // 8: pipeline.ThumbnailRequested
	(*ThumbnailCompleted)(nil),   // 9: pipeline.ThumbnailCompleted
	(*ThumbnailFailed)(nil),      // 10: pipeline.ThumbnailFailed
	(*StoryboardRequested)(nil),  // 11: pipeline.StoryboardRequested
	(*StoryboardCompleted)(nil),  // 12: pipeline.StoryboardCompleted
	(*StoryboardFailed)(nil),     // 13: pipeline.StoryboardFailed
	(*SubtitleRequested)(nil),    // 14: pipeline.SubtitleRequested
	(*SubtitleCompleted)(nil),    // 15: pipeline.SubtitleCompleted
	(*SubtitleFailed)(nil),       // 16: pipeline.SubtitleFailed
	(*PipelineRunCompleted)(nil), // 17: pipeline.PipelineRunCompleted
	(*PipelineRunFailed)(nil),    // 18: pipeline.PipelineRunFailed
	nil,                          // 19: pipeline.PipelineRunCompleted.ArtifactLocationsEntry
}
var file_pipeline_proto_depIdxs = []int32{
	2,  // 0: pipeline.ProbeCompleted.result:type_name -> pipeline.ProbeResult
	19, // 1: pipeline.PipelineRunCompleted.artifact_locations:type_name -> pipeline.PipelineRunCompleted.ArtifactLocationsEntry
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_pipeline_proto_init() }
func file_pipeline_proto_init() {
	if File_pipeline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pipeline_proto_rawDesc), len(file_pipeline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pipeline_proto_goTypes,
		DependencyIndexes: file_pipeline_proto_depIdxs,
		MessageInfos:      file_pipeline_proto_msgTypes,
	}.Build()
	File_pipeline_proto = out.File
	file_pipeline_proto_goTypes = nil
	file_pipeline_proto_depIdxs = nil
}
